# Generated by Django 2.2.5 on 2019-09-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrackUserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_detail',
            table='user_details',
        ),
    ]
